cmake        -D SHELL="/bin/bash -x" \
             -D CMAKE_BUILD_TYPE=RELEASE \
             -D ENABLE_GNU_STL_DEBUG=OFF \
             -D OPENCV_GENERATE_PKGCONFIG=ON \
             -D CMAKE_C_COMPILER=/usr/bin/gcc \
             -D CMAKE_CXX_COMPILER=/usr/bin/g++ \
             -D CMAKE_CPP_COMPILER=/usr/bin/cpp \
             -D CMAKE_CXX_STANDARD=14 \
             -D ENABLE_CXX11=OFF \
			       -D BUILD_ZLIB=ON \
             -D WITH_TIFF=OFF \
	           -D BUILD_JPEG=ON \
             -D BUILD_PNG=ON \
             -D BUILD_WEBP=ON \
			       -D Tesseract_DIR="/usr/share/tesseract-ocr/4.00" \
			       -D WITH_TESSERACT=ON \
             -D BUILD_SHARED_LIBS=OFF \
             -D ENABLE_FAST_MATH=1 \
             -D BUILD_opencv_python=OFF \
             -D INSTALL_PYTHON_EXAMPLES=OFF \
             -D INSTALL_C_EXAMPLES=OFF \
             -D BUILD_EXAMPLES=OFF \
             -D OPENCV_GENERATE_PKGCONFIG=ON \
             -D WITH_GTK=true \
		       	 -D BUILD_TBB=OFF \
             -D WITH_TBB=ON \
             -D WITH_OPENMP=OFF  \
             -D WITH_EIGEN=ON \
             -D WITH_IPP=ON \
             -D OPENCV_ENABLE_NONFREE=ON \
             -D BUILD_opencv_apps=ON \
             -D WITH_V4L=ON \
             -D WITH_QT=OFF \
             -D BUILD_opencv_java=ON \
             -D BUILD_JAVA=ON \
             -D JAVA_INCLUDE_PATH2="/home/spedison/.sdkman/candidates/java/current/include/linux" \
             -D BUILD_FAT_JAVA_LIB=ON \
             -D WITH_CSTRIPES=ON  \
             -D BUILD_opencv_viz=ON \
             -D WITH_FFMPEG=ON  \
             -D WITH_OPENGL=ON \
             -D WITH_VA_INTEL=ON \
             -D WITH_GSTREAMER=ON \
             -D BUILD_DOCS=OFF  \
             -D BUILD_PERF_TESTS=OFF  \
             -D BUILD_TESTS=ON  \
             -D OPENCV_GENERATE_PKGCONFIG=ON \
             -D OPENCV_PC_FILE_NAME=opencv.pc \
             -D FFMPEG_LIBDIR="/usr/lib/x86_64-linux-gnu" \
             -D FFMPEG_INCLUDE_DIRS="/usr/include/" \
             -D CMAKE_INSTALL_PREFIX="/home/spedison/libs/opencv"  \
             -D OPENCV_EXTRA_MODULES_PATH="../opencv_contrib/modules" \
             -D WITH_CUDA=OFF \
             -D OPENCV_DNN_OPENCL=ON \
			       -D OPENCV_TEST_DNN_TIMVX=OFF \
		       	 -D OPENCV_TEST_DNN_TFLITE=OFF \
		      	 -D OPENCV_TEST_DNN_OPENVINO=OFF \
		      	 -D OPENCV_TEST_DNN_CANN=OFF \
             -D WITH_OPENCL=ON \
             ../opencv

## TODO: Add this options
#             -D CUDA_FAST_MATH=OFF \
#             -D WITH_CUBLAS=OFF \
#             -D BUILD_opencv_cudacodec=OFF \
#             -D WITH_CUDNN=OFF -D OPENCV_DNN_CUDA=OF \
#	     -D WITH_CUFFT=OFF  \
#             -D WITH_NVCUVID=OFF  \
             
